<a href="https://colab.research.google.com/github/24Sinchana/project/blob/main/ML%20PROJECTS/Movie_Recommendation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import difflib  #find close match of the movie name or values (compare)
from sklearn.feature_extraction.text import TfidfVectorizer #convert text to numerical data
from sklearn.metrics.pairwise import cosine_similarity # gives similarity score

In [ ]:
#data collection and preprocessing
#loading data from csv file to pandas adateframe
movies_data=pd.read_csv("movies.csv")

In [ ]:
movies_data.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [ ]:
movies_data.shape

(4803, 24)

In [ ]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [ ]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
#selecting relavent features
selected_features=['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [ ]:
#replace null values with null string
for feature in selected_features:
    movies_data[feature]=movies_data[feature].fillna('')

In [ ]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [ ]:
#combing all selected_features
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+ ''+movies_data['director']

In [ ]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [ ]:
#converting text dat to feature vectors
vectorizer=TfidfVectorizer()

In [ ]:
feature_vector=vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vector)

  (0, 208)	0.07667385108184376
  (0, 289)	0.08800104830707552
  (0, 6241)	0.1083630860656862
  (0, 16345)	0.10110130418423781
  (0, 6437)	0.10110130418423781
  (0, 4357)	0.2086788913449303
  (0, 3615)	0.21664083919579374
  (0, 6923)	0.1606391519765174
  (0, 17262)	0.33130376319063676
  (0, 19787)	0.12241864673585882
  (0, 3806)	0.24348426965339803
  (0, 17147)	0.2086788913449303
  (0, 5865)	0.23437015044361997
  (0, 18275)	0.06921925370543773
  (0, 20389)	0.12507033381973537
  (0, 13517)	0.08827534630310274
  (0, 13860)	0.26544401841252097
  (0, 16062)	0.15564527461690644
  (0, 20398)	0.23860058795491665
  (0, 20721)	0.19702892145320783
  (0, 16029)	0.21898867021233073
  (0, 16879)	0.20091311266965015
  (0, 19900)	0.19827148152003798
  (0, 17532)	0.16181995525842374
  (0, 10559)	0.22730069036139045
  :	:
  (4801, 423)	0.19056341009568284
  (4801, 5734)	0.2563183496274323
  (4801, 20694)	0.29933113097807007
  (4801, 16621)	0.28905348514055085
  (4801, 20559)	0.3138166592040448
  (4801, 4145)	0.3138166592040448
  (4801, 15864)	0.3138166592040448
  (4801, 16765)	0.3138166592040448
  (4801, 8776)	0.3138166592040448
  (4802, 13485)	0.1812883618371389
  (4802, 5347)	0.17030049967383565
  (4802, 2454)	0.1755983510178846
  (4802, 5908)	0.1712024779337688
  (4802, 7301)	0.18320658286238686
  (4802, 4057)	0.22511280012954266
  (4802, 5357)	0.19894359173578305
  (4802, 1488)	0.20002303752562678
  (4802, 15620)	0.17612508460823412
  (4802, 5167)	0.15607460606564647
  (4802, 2856)	0.24353543417297582
  (4802, 7663)	0.23018746318092126
  (4802, 4323)	0.26635394130052475
  (4802, 6353)	0.23965799931641568
  (4802, 8414)	0.5783448968561475
  (4802, 5463)	0.28917244842807377

In [ ]:
# Cosine similarity-getting similarity scores
similarity=cosine_similarity(feature_vector)

In [ ]:
print(similarity)

[[1.         0.07047992 0.01423497 ... 0.         0.         0.        ]
 [0.07047992 1.         0.03271772 ... 0.03557523 0.         0.        ]
 [0.01423497 0.03271772 1.         ... 0.         0.02997687 0.        ]
 ...
 [0.         0.03557523 0.         ... 1.         0.         0.02941525]
 [0.         0.         0.02997687 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02941525 0.         1.        ]]

In [ ]:
print(similarity.shape)

(4803, 4803)

In [ ]:
#index and similarity score

In [ ]:
#first number represents the index of the movie ,second value represents the similarity score of iron man movie with other movie

Movie Recommendation System

In [22]:
movie_name=input("enter your favourite movie name:")

list_of_all_titles=movies_data['title'].tolist()

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
index_of_movie = movies_data[movies_data.title == close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_of_movie]))

sorted_similar_movies=sorted(similarity_score, key = lambda x:x[1],reverse=True)


print("Movies suggested for you:")
i=1
for movie in sorted_similar_movies:

    index=movie[0] #represent first value(0,1.0000)
    title_from_index=movies_data[movies_data.index==index]['title'].values[0]
    if(i<30):   #first 30 similar movies
        print(i,'.',title_from_index)
        i+=1

enter your favourite movie name:bat man
Movies suggested for you:
1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . A History of Violence
8 . Superman
9 . Bedazzled
10 . Man of Steel
11 . Suicide Squad
12 . Beetlejuice
13 . The Postman Always Rings Twice
14 . Salton Sea
15 . Jonah Hex
16 . Spider-Man 3
17 . Superman Returns
18 . Mars Attacks!
19 . Spider-Man 2
20 . Exorcist II: The Heretic
21 . Reds
22 . Superman III
23 . Superman II
24 . Something's Gotta Give
25 . Multiplicity
26 . I Dreamed of Africa
27 . Catwoman
28 . Batman Forever
29 . The One