<a href="https://colab.research.google.com/github/24Sinchana/project/blob/main/ML%20PROJECTS/Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import difflib  #find close match of the movie name or values (compare)
from sklearn.feature_extraction.text import TfidfVectorizer #convert text to numerical data
from sklearn.metrics.pairwise import cosine_similarity # gives similarity score

In [4]:
#data collection and preprocessing
#loading data from csv file to pandas adateframe
movies_data=pd.read_csv("movies.csv")

In [5]:
movies_data.head()

   index     budget  ...                                               crew           director
0      0  237000000  ...  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1      1  300000000  ...  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2      2  245000000  ...  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3      3  250000000  ...  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4      4  260000000  ...  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

In [6]:
movies_data.shape

(4803, 24)

In [7]:
movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [8]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [9]:
#selecting relavent features
selected_features=['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [10]:
#replace null values with null string
for feature in selected_features:
    movies_data[feature]=movies_data[feature].fillna('')

In [11]:
movies_data.head()

   index     budget  ...                                               crew           director
0      0  237000000  ...  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1      1  300000000  ...  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2      2  245000000  ...  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3      3  250000000  ...  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4      4  260000000  ...  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

In [12]:
movies_data.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [14]:
#combing all selected_features
combined_features=movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+ ''+movies_data['director']

In [15]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [16]:
#converting text dat to feature vectors
vectorizer=TfidfVectorizer()

In [17]:
feature_vector=vectorizer.fit_transform(combined_features)

In [18]:
print(feature_vector)

  (0, 208)	0.07667385108184376
  (0, 289)	0.08800104830707552
  (0, 6241)	0.1083630860656862
  (0, 16345)	0.10110130418423781
  (0, 6437)	0.10110130418423781
  (0, 4357)	0.2086788913449303
  (0, 3615)	0.21664083919579374
  (0, 6923)	0.1606391519765174
  (0, 17262)	0.33130376319063676
  (0, 19787)	0.12241864673585882
  (0, 3806)	0.24348426965339803
  (0, 17147)	0.2086788913449303
  (0, 5865)	0.23437015044361997
  (0, 18275)	0.06921925370543773
  (0, 20389)	0.12507033381973537
  (0, 13517)	0.08827534630310274
  (0, 13860)	0.26544401841252097
  (0, 16062)	0.15564527461690644
  (0, 20398)	0.23860058795491665
  (0, 20721)	0.19702892145320783
  (0, 16029)	0.21898867021233073
  (0, 16879)	0.20091311266965015
  (0, 19900)	0.19827148152003798
  (0, 17532)	0.16181995525842374
  (0, 10559)	0.22730069036139045
  :	:
  (4801, 423)	0.19056341009568284
  (4801, 5734)	0.2563183496274323
  (4801, 20694)	0.29933113097807007
  (4801, 16621)	0.28905348514055085
  (4801, 20559)	0.3138166592040448
  (4801, 4145)	0.3138166592040448
  (4801, 15864)	0.3138166592040448
  (4801, 16765)	0.3138166592040448
  (4801, 8776)	0.3138166592040448
  (4802, 13485)	0.1812883618371389
  (4802, 5347)	0.17030049967383565
  (4802, 2454)	0.1755983510178846
  (4802, 5908)	0.1712024779337688
  (4802, 7301)	0.18320658286238686
  (4802, 4057)	0.22511280012954266
  (4802, 5357)	0.19894359173578305
  (4802, 1488)	0.20002303752562678
  (4802, 15620)	0.17612508460823412
  (4802, 5167)	0.15607460606564647
  (4802, 2856)	0.24353543417297582
  (4802, 7663)	0.23018746318092126
  (4802, 4323)	0.26635394130052475
  (4802, 6353)	0.23965799931641568
  (4802, 8414)	0.5783448968561475
  (4802, 5463)	0.28917244842807377

In [19]:
# Cosine similarity-getting similarity scores
similarity=cosine_similarity(feature_vector)

In [20]:
print(similarity)

[[1.         0.07047992 0.01423497 ... 0.         0.         0.        ]
 [0.07047992 1.         0.03271772 ... 0.03557523 0.         0.        ]
 [0.01423497 0.03271772 1.         ... 0.         0.02997687 0.        ]
 ...
 [0.         0.03557523 0.         ... 1.         0.         0.02941525]
 [0.         0.         0.02997687 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02941525 0.         1.        ]]

In [21]:
print(similarity.shape)

(4803, 4803)

In [22]:
#index and similarity score

In [23]:
#getting movie name from user
movie_name=input("enter your favourite movie name:")

enter your favourite movie name:iron man

In [24]:
#creating list of all movies name
list_of_all_titles=movies_data['title'].tolist() #creates a list

In [25]:
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [27]:
#finding close match for the movie name given by user
find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)

In [28]:
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']

In [31]:
close_match=find_close_match[0]
print(close_match)  #most relavent

Iron Man

In [34]:
#find the corresponding index of the movie with title
index_of_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_movie)

68

In [49]:
#getting list of similar movies
#enumerate to carry loop in the list
similarity_score=list(enumerate(similarity[index_of_movie]))
print(similarity_score)

[(0, 0.03229579644860707), (1, 0.05393195039447942), (2, 0.013495256913644414), (3, 0.006290137712561313), (4, 0.03181599223363476), (5, 0.013492855232607511), (6, 0.0807002229078615), (7, 0.23948092153801243), (8, 0.007641303920257968), (9, 0.07528320175535286), (10, 0.07440697853473807), (11, 0.011816684330342166), (12, 0.01349314196279947), (13, 0.01219543022207434), (14, 0.09532110167793535), (15, 0.007191559327707054), (16, 0.22696359695614313), (17, 0.012738836763260195), (18, 0.040336420677614754), (19, 0.07763620585984603), (20, 0.07702266637203237), (21, 0.011076120703301915), (22, 0.006787153718668808), (23, 0.006402612273657428), (24, 0.01226292406425624), (25, 0.0), (26, 0.21748863690185471), (27, 0.029945938769572685), (28, 0.06190026789378868), (29, 0.013589845716434311), (30, 0.07814636293349293), (31, 0.27155401360493714), (32, 0.028052126365086392), (33, 0.129125151923067), (34, 0.0), (35, 0.03417250378858465), (36, 0.031252233451102195), (37, 0.007885689399278514), (38, 0.10906527471967553), (39, 0.09105059494424492), (40, 0.007869506437751519), (41, 0.06245579295095424), (42, 0.0), (43, 0.02590880432131621), (44, 0.006020155038682655), (45, 0.023149949171852945), (46, 0.1399174245717579), (47, 0.035682533300910674), (48, 0.013531221842048505), (49, 0.0), (50, 0.012869769058928542), (51, 0.027432051694699693), (52, 0.029558620317564926), (53, 0.021689371000382207), (54, 0.04905815837527673), (55, 0.01405193010632707), (56, 0.03667875158044711), (57, 0.038306195801103726), (58, 0.006567793123068909), (59, 0.031169185955729664), (60, 0.0), (61, 0.03333081304288371), (62, 0.01294532433541674), (63, 0.006886339490673711), (64, 0.15008682959582387), (65, 0.005736913110239847), (66, 0.007117886193988723), (67, 0.028230384122127007), (68, 1.0000000000000004), (69, 0.012765296453154464), (70, 0.03215936323229855), (71, 0.017031611255412436), (72, 0.06947945753525048), (73, 0.0), (74, 0.025501743558833494), (75, 0.012786181908456373), (76, 0.05009533900072807), (77, 0.0), (78, 0.061141520542362604), (79, 0.348539886661646), (80, 0.008115123621499389), (81, 0.01014014434203295), (82, 0.026753415454277014), (83, 0.03460853747385219), (84, 0.010874467124379814), (85, 0.20384498126302353), (86, 0.006320274766127612), (87, 0.026679850773634016), (88, 0.012832934386631682), (89, 0.006497705904545083), (90, 0.007311568411485809), (91, 0.07447515952431612), (92, 0.015254840747526258), (93, 0.024338494863953446), (94, 0.13105605324769884), (95, 0.06081426940379865), (96, 0.03288355742310937), (97, 0.026391290678116568), (98, 0.04758378838931776), (99, 0.005481273287331274), (100, 0.0), (101, 0.13929773066794668), (102, 0.034861679342918214), (103, 0.013426455762701866), (104, 0.013641061891414497), (105, 0.0), (106, 0.007730872362908813), (107, 0.029610515548111373), (108, 0.03261606772570161), (109, 0.0054161060951491225), (110, 0.019057967824565085), (111, 0.03427889964378965), (112, 0.01296866196275424), (113, 0.007467385596467177), (114, 0.0068505218073905355), (115, 0.005478574473227641), (116, 0.023105284255351903), (117, 0.006795429118001041), (118, 0.0), (119, 0.005904829342916091), (120, 0.0), (121, 0.012216495352641004), (122, 0.10626607781771327), (123, 0.030785532125086872), (124, 0.0066830185502500606), (125, 0.030868053059685638), (126, 0.1309077781595354), (127, 0.034972189384000665), (128, 0.03189065672879913), (129, 0.07990014869116349), (130, 0.006631125430057233), (131, 0.10937368345102097), (132, 0.006879958746955824), (133, 0.0), (134, 0.012355694176917576), (135, 0.0), (136, 0.041526517677495274), (137, 0.0), (138, 0.058513335469189916), (139, 0.011650742038099023), (140, 0.005861592028405673), (141, 0.007351787454346134), (142, 0.008019024437444676), (143, 0.007650016987415756), (144, 0.007496468899776052), (145, 0.006208382224956433), (146, 0.03027982428539639), (147, 0.011793625418680322), (148, 0.0056287987567508095), (149, 0.03133111699857222), (150, 0.03174893989603526), (151, 0.012674757870660155), (152, 0.012246629000364613), (153, 0.012298531032504702), (154, 0.0), (155, 0.0), (156, 0.004689151151531666), (157, 0.013909968553907484), (158, 0.034125027351165925), (159, 0.0053101410165348525), (160, 0.013231060742508391), (161, 0.0), (162, 0.006902972574308775), (163, 0.049574553373342406), (164, 0.01893229820952239), (165, 0.028273144719267652), (166, 0.03815022081135573), (167, 0.02077375747938036), (168, 0.031873786210526306), (169, 0.13514452526336213), (170, 0.023268472600766758), (171, 0.006813948473642546), (172, 0.021526387945561543), (173, 0.0), (174, 0.14326369370437603), (175, 0.007114315579566796), (176, 0.006870041729626001), (177, 0.0), (178, 0.04324306927683931), (179, 0.007624640777170078), (180, 0.006037372645243663), (181, 0.007644072123228718), (182, 0.19211495786414462), (183, 0.034220473105458164), (184, 0.021543946810311423), (185, 0.06659608812819669), (186, 0.011329305174663986), (187, 0.019629067357825485), (188, 0.0059183547262031426), (189, 0.008227638939979595), (190, 0.013939846340225714), (191, 0.007289573800622664), (192, 0.0), (193, 0.0346103028298725), (194, 0.0), (195, 0.007140911554501998), (196, 0.02624692415843478), (197, 0.007584666030411901), (198, 0.06863363936999158), (199, 0.04867572719915833), (200, 0.02802386402300029), (201, 0.031742888306347056), (202, 0.007177361189176771), (203, 0.14651794298050327), (204, 0.005715420192222998), (205, 0.08959603092551782), (206, 0.012231681035556457), (207, 0.0461546297514076), (208, 0.012394537711311944), (209, 0.005848533074609841), (210, 0.005444401217635256), (211, 0.029391423015051654), (212, 0.031211324999396987), (213, 0.014230139936139283), (214, 0.0), (215, 0.013820616451945503), (216, 0.012450921225237388), (217, 0.005374418778165852), (218, 0.006562367189727748), (219, 0.03112708021457932), (220, 0.02428981266173267), (221, 0.007981045053407191), (222, 0.026542189167100813), (223, 0.023106463554097456), (224, 0.02442578412259655), (225, 0.02892117260947699), (226, 0.0), (227, 0.005577327590772642), (228, 0.030922447007768084), (229, 0.03326927176771207), (230, 0.0257252370801356), (231, 0.0), (232, 0.08987441987195353), (233, 0.027170820633253358), (234, 0.007624857252759041), (235, 0.006956254355017057), (236, 0.005610075714060779), (237, 0.012346321835090157), (238, 0.06525519536926602), (239, 0.018068748457346868), (240, 0.013238683212224217), (241, 0.04195182994268593), (242, 0.1041908336844519), (243, 0.013027532559260473), (244, 0.004806088758723313), (245, 0.011311133862094697), (246, 0.005344009105325208), (247, 0.0), (248, 0.0058995117345094425), (249, 0.027128481794969156), (250, 0.0), (251, 0.0), (252, 0.005821056086414123), (253, 0.004844829799818892), (254, 0.03488381623364998), (255, 0.0), (256, 0.02679505630702151), (257, 0.0251445565052339), (258, 0.0), (259, 0.011881686243814233), (260, 0.03268952875164524), (261, 0.006387717535168037), (262, 0.049566977039335845), (263, 0.027171939340130187), (264, 0.0), (265, 0.0), (266, 0.025608291432904266), (267, 0.010843840829865753), (268, 0.0), (269, 0.0), (270, 0.05816056897545989), (271, 0.035269856425193244), (272, 0.0), (273, 0.005339523295451836), (274, 0.013949579730148742), (275, 0.023726681308593126), (276, 0.0074764958617573275), (277, 0.012952954896416742), (278, 0.06449198646548476), (279, 0.04258232576816475), (280, 0.0), (281, 0.0), (282, 0.005063205903758669), (283, 0.0), (284, 0.014926775141888206), (285, 0.00514962631131896), (286, 0.021130753069504356), (287, 0.0), (288, 0.0), (289, 0.007128192660168227), (290, 0.013498413873412766), (291, 0.01887118789271873), (292, 0.02350065189568143), (293, 0.0), (294, 0.008042665670867975), (295, 0.005535717119985946), (296, 0.005952408149378009), (297, 0.0058276471462949935), (298, 0.0), (299, 0.005822467194068284), (300, 0.026856805141405045), (301, 0.02061461803367109), (302, 0.007496252119711359), (303, 0.005931776899446102), (304, 0.01256332731871675), (305, 0.02718581588023705), (306, 0.02765504464143632), (307, 0.09106924634096375), (308, 0.004911167550341964), (309, 0.04106855579948218), (310, 0.042038794331822824), (311, 0.032415558772335804), (312, 0.011466761550065015), (313, 0.026512773021282375), (314, 0.0), (315, 0.011593991463072335), (316, 0.040144814564046824), (317, 0.0), (318, 0.05652876152343031), (319, 0.026785619897612675), (320, 0.005743105802117715), (321, 0.0), (322, 0.03439875835733343), (323, 0.0), (324, 0.04491371105674552), (325, 0.010957933929942773), (326, 0.0), (327, 0.0), (328, 0.03301626845221488), (329, 0.049951315677531985), (330, 0.05124490162332733), (331, 0.05183883051458321), (332, 0.042431540879873136), (333, 0.01735627137560163), (334, 0.030682150193678474), (335, 0.025365648045366812), (336, 0.0067979146739607695), (337, 0.0037305465488754494), (338, 0.0), (339, 0.01387825572399414), (340, 0.01612226263962279), (341, 0.007076825642170294), (342, 0.02997572783442531), (343, 0.0), (344, 0.0047225506566791016), (345, 0.03045947981854056), (346, 0.0), (347, 0.01151901531195396), (348, 0.007362957202075732), (349, 0.007051577715849965), (350, 0.022626937268800197), (351, 0.0), (352, 0.0069497816795443725), (353, 0.11301836236268734), (354, 0.0), (355, 0.005845129032182711), (356, 0.09031668626687421), (357, 0.0), (358, 0.025122040690366814), (359, 0.0073065259249785785), (360, 0.01656427855388245), (361, 0.08192388810660685), (362, 0.026580766546355196), (363, 0.019028636554007893), (364, 0.0), (365, 0.01775657895246717), (366, 0.03096056708660701), (367, 0.0), (368, 0.0063936842490887125), (369, 0.010745025901340455), (370, 0.013220954234681897), (371, 0.026080660486806934), (372, 0.019530643104283093), (373, 0.020968022164040305), (374, 0.00667141831999737), (375, 0.01759227099622457), (376, 0.024395733345159664), (377, 0.02518034804176936), (378, 0.0), (379, 0.011178825810739819), (380, 0.026508922997980248), (381, 0.007184735709082704), (382, 0.06118238295323025), (383, 0.012315386668631263), (384, 0.00718138995387196), (385, 0.0), (386, 0.02327551996804664), (387, 0.005681079577856969), (388, 0.0), (389, 0.02232617666012063), (390, 0.0), (391, 0.0), (392, 0.005333671809343689), (393, 0.030310366226266695), (394, 0.005730346412337222), (395, 0.0), (396, 0.04782384454401522), (397, 0.0), (398, 0.0), (399, 0.006502048979363829), (400, 0.029081034183566667), (401, 0.07978698431239749), (402, 0.034186296896911925), (403, 0.0121989685961108), (404, 0.0), (405, 0.004447694232582915), (406, 0.0), (407, 0.0), (408, 0.005744842500746346), (409, 0.0), (410, 0.025915824763975297), (411, 0.010176239300636932), (412, 0.030368887821126046), (413, 0.020204967403395002), (414, 0.02903941163990793), (415, 0.02748488763466647), (416, 0.0), (417, 0.0), (418, 0.0), (419, 0.029623909851286826), (420, 0.05771263044247819), (421, 0.07410092724287355), (422, 0.01939646593586878), (423, 0.0), (424, 0.01365251103960191), (425, 0.014172518561301809), (426, 0.02545725971993652), (427, 0.0), (428, 0.0060355068297521745), (429, 0.0), (430, 0.0), (431, 0.0), (432, 0.020255236301932277), (433, 0.006202675130379578), (434, 0.0), (435, 0.0), (436, 0.06053044735347384), (437, 0.006205067808055184), (438, 0.0), (439, 0.0), (440, 0.01407354850083766), (441, 0.041445102299257686), (442, 0.021848708946730334), (443, 0.01558076707358016), (444, 0.0), (445, 0.0), (446, 0.03842332652308461), (447, 0.006077544764686449), (448, 0.0), (449, 0.023489176852172423), (450, 0.019264253074970372), (451, 0.03877802486356783), (452, 0.0), (453, 0.005925990620457937), (454, 0.016783785234575455), (455, 0.005516199548402431), (456, 0.005163560094786783), (457, 0.05131300327318994), (458, 0.0073365433506347895), (459, 0.032956709575202144), (460, 0.0), (461, 0.028433543829524097), (462, 0.0), (463, 0.0), (464, 0.04165423542488717), (465, 0.0), (466, 0.043514269215994925), (467, 0.01462937427829486), (468, 0.005487039741024071), (469, 0.011827376376234109), (470, 0.0205015917073975), (471, 0.018494989488635493), (472, 0.012695646777598756), (473, 0.01917736646327769), (474, 0.0), (475, 0.025020178566937834), (476, 0.025798165512563573), (477, 0.0), (478, 0.012910116417192212), (479, 0.015911039075606932), (480, 0.026274742612889534), (481, 0.0), (482, 0.0), (483, 0.04409084467474114), (484, 0.006632672398370357), (485, 0.0065999250322728445), (486, 0.012626454779755904), (487, 0.030448819097262776), (488, 0.013244876478088518), (489, 0.0), (490, 0.03135053334803914), (491, 0.01119043442416998), (492, 0.0), (493, 0.030005232584611016), (494, 0.006566367115605793), (495, 0.032342111764553184), (496, 0.0), (497, 0.0), (498, 0.006756817435624349), (499, 0.0), (500, 0.005345639629844824), (501, 0.07816561416436357), (502, 0.015218203451943267), (503, 0.031859257248628696), (504, 0.0170594368874769), (505, 0.02438450558961982), (506, 0.0), (507, 0.0579488553500522), (508, 0.05840146767306599), (509, 0.0), (510, 0.02534705101035825), (511, 0.16526444635810034), (512, 0.006071188197781375), (513, 0.010645957876293964), (514, 0.005540801974532237), (515, 0.0), (516, 0.0), (517, 0.0), (518, 0.014621032844403033), (519, 0.0), (520, 0.0), (521, 0.0), (522, 0.0), (523, 0.01325989788554514), (524, 0.0), (525, 0.018301513837790558), (526, 0.0), (527, 0.0), (528, 0.0042360389520069335), (529, 0.005139007212216797), (530, 0.0061722201665324735), (531, 0.012120637047418106), (532, 0.0), (533, 0.0), (534, 0.006341244630008373), (535, 0.012059284433037429), (536, 0.037120598421855375), (537, 0.005492056484244685), (538, 0.0), (539, 0.04342341108349522), (540, 0.016456491058406443), (541, 0.020155534807208973), (542, 0.02299698904634443), (543, 0.010910008434848077), (544, 0.012681437026311429), (545, 0.044215382470255186), (546, 0.022863272345553853), (547, 0.005899469507426471), (548, 0.0), (549, 0.01734652647585618), (550, 0.0), (551, 0.0071828567780874725), (552, 0.0), (553, 0.005744097833076607), (554, 0.0), (555, 0.0), (556, 0.0049617168411964915), (557, 0.0), (558, 0.0), (559, 0.0), (560, 0.019696763212979328), (561, 0.005201290442871416), (562, 0.028859761725330998), (563, 0.0), (564, 0.03513125399856418), (565, 0.007856684775455819), (566, 0.006566440663801155), (567, 0.0), (568, 0.012670986608048721), (569, 0.007531775544332097), (570, 0.03434021476177777), (571, 0.00523500480461971), (572, 0.007109735324637368), (573, 0.005979609803834964), (574, 0.04899240617585075), (575, 0.019908952187155358), (576, 0.0), (577, 0.02986396554311785), (578, 0.01674262423753176), (579, 0.0042391808315979836), (580, 0.005353621042978573), (581, 0.02985550112896601), (582, 0.024070075596610823), (583, 0.014120914949058818), (584, 0.0), (585, 0.0), (586, 0.004953077512120195), (587, 0.03402068016780752), (588, 0.0), (589, 0.005534651790555104), (590, 0.0054979886541612925), (591, 0.023306622311645115), (592, 0.006536174206542276), (593, 0.02963025095999405), (594, 0.01294903664974417), (595, 0.012080805061841837), (596, 0.013562967540239262), (597, 0.005565315901624048), (598, 0.0), (599, 0.06186435319192784), (600, 0.03306925301845963), (601, 0.026891455836907885), (602, 0.014964579244325916), (603, 0.0), (604, 0.01266397843573528), (605, 0.0), (606, 0.0), (607, 0.0732446765076957), (608, 0.0), (609, 0.02681003466592808), (610, 0.011873553394750113), (611, 0.005073531899222542), (612, 0.023848865891421735), (613, 0.01961938797567568), (614, 0.0), (615, 0.018463000418560117), (616, 0.0), (617, 0.006682090442561), (618, 0.10261732891660269), (619, 0.0), (620, 0.0), (621, 0.005128244608125171), (622, 0.005781157275880183), (623, 0.0), (624, 0.005077946283388535), (625, 0.0), (626, 0.02186131343505622), (627, 0.00979754355752437), (628, 0.0), (629, 0.0046305254289394976), (630, 0.0), (631, 0.052641239182580526), (632, 0.020545384688877687), (633, 0.0), (634, 0.02447912296947878), (635, 0.03164706390233992), (636, 0.0), (637, 0.0), (638, 0.0), (639, 0.01683810589849224), (640, 0.012566001068776152), (641, 0.07284133731186311), (642, 0.0), (643, 0.01333470018708625), (644, 0.020795261209204156), (645, 0.013377959717674326), (646, 0.014414109326224556), (647, 0.0), (648, 0.0), (649, 0.0), (650, 0.0), (651, 0.0), (652, 0.014102969775271089), (653, 0.00563572927601234), (654, 0.06632187947509255), (655, 0.005850844608959731), (656, 0.0), (657, 0.026024838767402737), (658, 0.023803850026083845), (659, 0.005808839411006173), (660, 0.01637862188675176), (661, 0.09419060854342598), (662, 0.0), (663, 0.0), (664, 0.04990643687538944), (665, 0.025679008681071813), (666, 0.0), (667, 0.0), (668, 0.03420620607704021), (669, 0.0), (670, 0.016914144919536855), (671, 0.006938886787557431), (672, 0.0), (673, 0.014625658246755855), (674, 0.07196007213047817), (675, 0.05731358104639431), (676, 0.012401807389291374), (677, 0.005471707849811078), (678, 0.015035324194787321), (679, 0.0), (680, 0.03847716493876165), (681, 0.0), (682, 0.0), (683, 0.011929330016369515), (684, 0.0), (685, 0.005636421287132184), (686, 0.0), (687, 0.012488916264668653), (688, 0.014598129662571955), (689, 0.0), (690, 0.0), (691, 0.0120272575586441), (692, 0.0), (693, 0.0), (694, 0.005347584208108454), (695, 0.011233491144110755), (696, 0.0), (697, 0.0), (698, 0.007957276190027469), (699, 0.02912045059822115), (700, 0.03523675513228662), (701, 0.02509059008978287), (702, 0.005610826550063906), (703, 0.013617771987422707), (704, 0.007382160137104965), (705, 0.0), (706, 0.023568280296109675), (707, 0.007499252539613367), (708, 0.00515441641064355), (709, 0.0), (710, 0.0), (711, 0.011035299414241593), (712, 0.0), (713, 0.015453719303354015), (714, 0.0), (715, 0.015104247603752074), (716, 0.019906085932584007), (717, 0.0), (718, 0.01988798113031363), (719, 0.0), (720, 0.05946518915691074), (721, 0.006738304401082989), (722, 0.0), (723, 0.016091162211236826), (724, 0.005470806352929808), (725, 0.07265857212828301), (726, 0.040956438559071495), (727, 0.0), (728, 0.05274981066086409), (729, 0.014852783702074598), (730, 0.006272341803102352), (731, 0.013586089685929028), (732, 0.036103802463419356), (733, 0.014004580540761844), (734, 0.006948168961876151), (735, 0.03174194204026017), (736, 0.0049159385544397995), (737, 0.005956473073082717), (738, 0.016315217920253148), (739, 0.005327777105473964), (740, 0.026254887896969583), (741, 0.005360083195671206), (742, 0.0), (743, 0.0), (744, 0.012825973874867263), (745, 0.005212576956416546), (746, 0.011413686883752737), (747, 0.005775041295842732), (748, 0.00779296946325537), (749, 0.0), (750, 0.007064023079566755), (751, 0.0), (752, 0.04095208909373935), (753, 0.005703434750471543), (754, 0.022836611212002013), (755, 0.03290541580445719), (756, 0.016239008636749604), (757, 0.0), (758, 0.0), (759, 0.0), (760, 0.016531057317371683), (761, 0.01868516585980355), (762, 0.005907160712943133), (763, 0.07639216407042232), (764, 0.0), (765, 0.0), (766, 0.0), (767, 0.01322902008046663), (768, 0.024903616619854067), (769, 0.009740409685361096), (770, 0.018224987204994297), (771, 0.015950164427514842), (772, 0.0), (773, 0.014812875065997492), (774, 0.024649764889697043), (775, 0.03125172381523368), (776, 0.0), (777, 0.027619074911807557), (778, 0.027229436845970914), (779, 0.0), (780, 0.02384256340518816), (781, 0.013810006595769217), (782, 0.0532754878521038), (783, 0.08043791581543272), (784, 0.014024352091822493), (785, 0.007463992377339546), (786, 0.014312420888907523), (787, 0.004675820806487655), (788, 0.13122776344970674), (789, 0.03927164223288428), (790, 0.005397733420176592), (791, 0.008211824008523156), (792, 0.0), (793, 0.020038495775342224), (794, 0.010532589529452793), (795, 0.0), (796, 0.0), (797, 0.025068723010783403), (798, 0.0), (799, 0.02897650736993783), (800, 0.07082543257643834), (801, 0.0), (802, 0.0), (803, 0.0), (804, 0.005781595392388011), (805, 0.06510872823457665), (806, 0.0), (807, 0.0058263905435204846), (808, 0.01291272785670648), (809, 0.0), (810, 0.0), (811, 0.014399892576025355), (812, 0.007222551887081216), (813, 0.031141635621381662), (814, 0.01785377805030897), (815, 0.0), (816, 0.007727812763131659), (817, 0.0), 

In [50]:
#first number represents the index of the movie ,second value represents the similarity score of iron man movie with other movie

In [51]:
len(similarity_score)

4803

In [52]:
#sorting based on similarity score
sorted_similar_movies=sorted(similarity_score, key = lambda x:x[1],reverse=True)

In [53]:
print(sorted_similar_movies) #decending order

[(68, 1.0000000000000004), (79, 0.348539886661646), (31, 0.27155401360493714), (7, 0.23948092153801243), (16, 0.22696359695614313), (26, 0.21748863690185471), (85, 0.20384498126302353), (182, 0.19211495786414462), (511, 0.16526444635810034), (64, 0.15008682959582387), (203, 0.14651794298050327), (174, 0.14326369370437603), (4401, 0.1430567313047247), (46, 0.1399174245717579), (101, 0.13929773066794668), (169, 0.13514452526336213), (788, 0.13122776344970674), (94, 0.13105605324769884), (126, 0.1309077781595354), (33, 0.129125151923067), (3623, 0.11773832986774722), (2442, 0.11576168742539061), (353, 0.11301836236268734), (131, 0.10937368345102097), (38, 0.10906527471967553), (1740, 0.10886177866608818), (122, 0.10626607781771327), (1451, 0.10557107626215012), (242, 0.1041908336844519), (618, 0.10261732891660269), (1210, 0.09932679833929622), (954, 0.09917190541875923), (2390, 0.098307771574909), (3166, 0.09732062356161367), (3385, 0.09710030708125605), (2235, 0.09697177344765094), (1406, 0.09683013909341812), (3443, 0.09640726824606835), (14, 0.09532110167793535), (661, 0.09419060854342598), (3116, 0.09276892746358262), (870, 0.09246477673056479), (1282, 0.09223378835557301), (3386, 0.0919812614825286), (1192, 0.09119417090025367), (307, 0.09106924634096375), (39, 0.09105059494424492), (2186, 0.09093550804378558), (882, 0.09048818198871211), (356, 0.09031668626687421), (232, 0.08987441987195353), (205, 0.08959603092551782), (1956, 0.08738769338233919), (3983, 0.0867006315477282), (1015, 0.08662004073400836), (2868, 0.08566789430226245), (940, 0.08520207105552749), (2063, 0.08438500251720119), (945, 0.08376467386239328), (4399, 0.08359355433231869), (2066, 0.08325146082530328), (1864, 0.08255834592947887), (1274, 0.0820763857155132), (3395, 0.08194230031560842), (361, 0.08192388810660685), (2411, 0.08170032689240067), (1135, 0.08096163377582058), (4542, 0.0808186344023539), (6, 0.0807002229078615), (783, 0.08043791581543272), (3092, 0.08007588771757052), (129, 0.07990014869116349), (401, 0.07978698431239749), (2625, 0.07957177861426447), (2447, 0.0794682101547444), (3106, 0.07943267597845671), (1428, 0.07919394997323358), (4450, 0.07897725969374961), (1029, 0.07884924684932709), (3211, 0.07835847539423459), (501, 0.07816561416436357), (30, 0.07814636293349293), (19, 0.07763620585984603), (20, 0.07702266637203237), (763, 0.07639216407042232), (3962, 0.07591025524096388), (9, 0.07528320175535286), (3231, 0.07497337743010411), (4033, 0.07474228736890286), (1651, 0.07462334513744628), (91, 0.07447515952431612), (10, 0.07440697853473807), (3286, 0.07417191847565527), (421, 0.07410092724287355), (1459, 0.0740707014629918), (2880, 0.07401934111243), (4759, 0.07379900267215475), (1972, 0.07362356149575905), (2648, 0.07338733513819781), (607, 0.0732446765076957), (1821, 0.07312999604585235), (641, 0.07284133731186311), (725, 0.07265857212828301), (2044, 0.07253414636914693), (4104, 0.07232038012004839), (3207, 0.07230338981986056), (1311, 0.07228493243986858), (4241, 0.07205349144775978), (674, 0.07196007213047817), (2221, 0.07161351987610354), (1317, 0.07138940000994529), (1664, 0.0711868563949592), (800, 0.07082543257643834), (3938, 0.07063247035838496), (72, 0.06947945753525048), (3989, 0.06914505634924067), (198, 0.06863363936999158), (2492, 0.06854697484985389), (1654, 0.06852374227779906), (840, 0.06841928822025814), (1553, 0.06836180512570861), (1230, 0.06763558417299265), (1365, 0.06756586268402934), (1128, 0.06705493825867287), (3172, 0.06686391167463283), (185, 0.06659608812819669), (1652, 0.06652614891034686), (654, 0.06632187947509255), (2598, 0.06627667075862974), (1368, 0.06579373340829488), (960, 0.06566948338802978), (3414, 0.06554682273499124), (2593, 0.06542904943548791), (1720, 0.06534557430515475), (238, 0.06525519536926602), (805, 0.06510872823457665), (3048, 0.06479520285761188), (1971, 0.06453170278840228), (278, 0.06449198646548476), (4149, 0.06419469855294459), (1277, 0.0631662009144536), (41, 0.06245579295095424), (2183, 0.062191044963190445), (1670, 0.06202347551455705), (28, 0.06190026789378868), (1874, 0.06189544325298506), (599, 0.06186435319192784), (4555, 0.06171733560588263), (4773, 0.06130296952082186), (382, 0.06118238295323025), (78, 0.061141520542362604), (95, 0.06081426940379865), (3853, 0.06076675604288484), (436, 0.06053044735347384), (2285, 0.05991665551280296), (3249, 0.059893611719611634), (1482, 0.05960853165371081), (3219, 0.05959557343940322), (720, 0.05946518915691074), (2326, 0.059434901802308364), (4364, 0.059303128524270825), (2607, 0.058952036052943746), (1502, 0.05866903279207121), (138, 0.058513335469189916), (4648, 0.05846561236304056), (508, 0.05840146767306599), (270, 0.05816056897545989), (1753, 0.05814368268328822), (2352, 0.05806648784628857), (507, 0.0579488553500522), (4045, 0.0579169749023733), (1573, 0.057783789742931344), (420, 0.05771263044247819), (675, 0.05731358104639431), (3802, 0.05702167859286261), (4284, 0.05676865883629638), (2127, 0.05673792127535949), (318, 0.05652876152343031), (1916, 0.05641898613361988), (2089, 0.05635666236336768), (3033, 0.056234012896653474), (2253, 0.055835420666554135), (3321, 0.05576530053297976), (1041, 0.05566205087340071), (3858, 0.0555138485192756), (3142, 0.0552180654446726), (1200, 0.055136513192012626), (4787, 0.055113504769197054), (3749, 0.054733880701613696), (2934, 0.054599878269174805), (1213, 0.05454599302386578), (4778, 0.054258496033717414), (1, 0.05393195039447942), (782, 0.0532754878521038), (2395, 0.05307300020564512), (1484, 0.052882024995971756), (728, 0.05274981066086409), (631, 0.052641239182580526), (331, 0.05183883051458321), (1165, 0.051600076262279346), (457, 0.05131300327318994), (3777, 0.05129091174101196), (330, 0.05124490162332733), (2805, 0.0510553110955775), (2525, 0.050955184920138744), (2822, 0.05082153841542525), (2823, 0.05073252351399181), (1978, 0.050713385201495854), (2039, 0.05064562126833903), (2164, 0.05060235959976936), (833, 0.050393757449785276), (76, 0.05009533900072807), (1703, 0.049968913058073314), (329, 0.049951315677531985), (664, 0.04990643687538944), (2364, 0.049893836754626344), (163, 0.049574553373342406), (262, 0.049566977039335845), (1715, 0.0494406422662903), (4714, 0.04915664835631726), (956, 0.04915307916558191), (4395, 0.049139836533605645), (54, 0.04905815837527673), (574, 0.04899240617585075), (199, 0.04867572719915833), (3494, 0.0486693478357234), (2937, 0.04860788199495027), (1016, 0.048450829057274755), (873, 0.04837833467583118), (1358, 0.04834188656224968), (953, 0.048084473842385), (1024, 0.047893706501086125), (396, 0.04782384454401522), (1086, 0.04781691259192261), (98, 0.04758378838931776), (911, 0.047507604961877115), (3105, 0.04742363179527418), (3643, 0.047379608537481056), (2875, 0.047370017719538825), (2046, 0.047259855668466), (3002, 0.04725544611772557), (3059, 0.04706700905326286), (1650, 0.04652309632565798), (3751, 0.046355889103471416), (1967, 0.04625694780203855), (4002, 0.04617208101836999), (207, 0.0461546297514076), (4599, 0.04607957612428541), (4671, 0.045915751840129734), (2544, 0.04588661683583641), (1494, 0.045658543510664076), (2138, 0.04545251314843489), (3184, 0.045328553969344924), (3354, 0.045295320011600006), (2129, 0.04521346895675243), (324, 0.04491371105674552), (3195, 0.044911636245223936), (977, 0.04473895325707933), (4579, 0.04447991315019874), (3867, 0.04447159272797724), (1398, 0.04445432322784626), (545, 0.044215382470255186), (1272, 0.04418983452596082), (4337, 0.04417797009675243), (483, 0.04409084467474114), (1604, 0.04382827797247679), (4772, 0.04364811467470652), (466, 0.043514269215994925), (539, 0.04342341108349522), (1932, 0.043327582362657005), (2107, 0.04331474589613332), (178, 0.04324306927683931), (3190, 0.04310865813023651), (4280, 0.04303376704750865), (1249, 0.04298388259773754), (1899, 0.042629866251065164), (279, 0.04258232576816475), (332, 0.042431540879873136), (3463, 0.04227736869883855), (2665, 0.0421523267377642), (1152, 0.04208537914551275), (310, 0.042038794331822824), (2964, 0.04203857747786741), (4414, 0.04200848644703932), (241, 0.04195182994268593), (2848, 0.041950134306526374), (2612, 0.04174610396614895), (464, 0.04165423542488717), (136, 0.041526517677495274), (2991, 0.04147684209718143), (441, 0.041445102299257686), (1990, 0.041384816398866944), (1696, 0.04130175477332992), (1039, 0.04115408845960576), (309, 0.04106855579948218), (726, 0.040956438559071495), (752, 0.04095208909373935), (929, 0.04089350032605231), (3942, 0.040795982360168036), (2778, 0.04079308006536828), (4072, 0.040781262548672266), (3267, 0.040734444316870906), (3812, 0.040661879158862234), (3607, 0.04064109323560029), (3825, 0.040348802051395155), (18, 0.040336420677614754), (2487, 0.040318478850392095), (3556, 0.040266676604499875), (2581, 0.04020288123895432), (3568, 0.040186083566392215), (316, 0.040144814564046824), (2405, 0.04011399342290024), (3819, 0.040019084601693435), (3612, 0.040017749008220915), (2145, 0.039644676826758894), (3347, 0.03962743047714555), (2346, 0.0395767272462321), (1170, 0.039557678204905994), (2410, 0.0395367656579012), (3069, 0.03947386001854482), (1396, 0.03935093005885906), (2987, 0.03931505740303569), (789, 0.03927164223288428), (1636, 0.039174230338265476), (2151, 0.039152446776251404), (2397, 0.03909971426506329), (3083, 0.0390851500726065), (3908, 0.03908448629516725), (1865, 0.03891993565361835), (4646, 0.03879886094676739), (1055, 0.03877889771333855), (451, 0.03877802486356783), (3828, 0.038692377361999306), (4183, 0.03865870548823168), (680, 0.03847716493876165), (446, 0.03842332652308461), (3469, 0.038311813563469126), (57, 0.038306195801103726), (1710, 0.03823793779240064), (166, 0.03815022081135573), (3012, 0.03802881282580936), (3160, 0.03782779990803342), (3616, 0.03763810219628287), (2028, 0.037583144753463534), (3133, 0.037526456043780784), (1542, 0.0375159615674788), (3274, 0.03741177938436459), (855, 0.03739510121444089), (1780, 0.03730426064871798), (4798, 0.037242920582432115), (4312, 0.0371707113523061), (536, 0.037120598421855375), (2317, 0.036978837377542), (3993, 0.0369549327680163), (2114, 0.036702693771970815), (56, 0.03667875158044711), (3442, 0.03661612828115328), (3699, 0.036589576339134365), (2043, 0.03654431889150332), (2651, 0.03649676028136635), (1247, 0.0364263103445243), (732, 0.036103802463419356), (1324, 0.03605874794392512), (1469, 0.03592131772928875), (2228, 0.03585195648631263), (2706, 0.03580140541514073), (3150, 0.03574799327772106), (3816, 0.03574747151062124), (2270, 0.0356927263224488), (47, 0.035682533300910674), (4193, 0.03567651591333408), (2387, 0.03564556271375821), (864, 0.03563913383356821), (4479, 0.03561519789834916), (3208, 0.035607604479554425), (1445, 0.03557111209541413), (1097, 0.035539570755889816), (2967, 0.03548599324826771), (2841, 0.035450954726990946), (4256, 0.035419749506835546), (2060, 0.03531455342872872), (271, 0.035269856425193244), (2335, 0.03524525312409002), (700, 0.03523675513228662), (4343, 0.03523135788402528), (1456, 0.035175387857531284), (564, 0.03513125399856418), (3866, 0.0350789523727244), (127, 0.034972189384000665), (1802, 0.03495241329425357), (1180, 0.03493214615021602), (2580, 0.034911927094895684), (1052, 0.03490879399553341), (254, 0.03488381623364998), (102, 0.034861679342918214), (193, 0.0346103028298725), (83, 0.03460853747385219), (4117, 0.03459795998920755), (4535, 0.03442773543735902), (1291, 0.03442137132130745), (322, 0.03439875835733343), (3561, 0.03438677665219016), (3981, 0.034349152122911286), (570, 0.03434021476177777), (111, 0.03427889964378965), (3652, 0.034258768467796005), (183, 0.034220473105458164), (1083, 0.0342161365609549), (668, 0.03420620607704021), (2630, 0.03420562134420242), (402, 0.034186296896911925), (35, 0.03417250378858465), (1794, 0.03416285440447482), (4563, 0.03415555981948097), (1233, 0.034148421948635085), (3204, 0.034138752340236375), (158, 0.034125027351165925), (976, 0.034120340680597716), (2444, 0.0340705427845652), (587, 0.03402068016780752), (3594, 0.034015437858848606), (1390, 0.0340073276619362), (1872, 0.03399228162501802), (3224, 0.033859685392222755), (4758, 0.03382168820966093), (3466, 0.03371581036169125), (2845, 0.033648017765139385), (4608, 0.03361866489165088), (2007, 0.03340430373500419), (61, 0.03333081304288371), (229, 0.03326927176771207), (972, 0.033209754436456115), (2605, 0.033202810756648826), (2314, 0.03318524270688579), (2101, 0.033081739581785036), (600, 0.03306925301845963), (3013, 0.03305698735200603), (1583, 0.033020775882857116), (328, 0.03301626845221488), (459, 0.032956709575202144), (1367, 0.032931076689916336), (755, 0.03290541580445719), (1490, 0.032895786522066435), (96, 0.03288355742310937), (4670, 0.03278867865292823), (3885, 0.03274521603545399), (1495, 0.03269868885991334), (260, 0.03268952875164524), (1782, 0.03264933977346019), (2966, 0.032623567768786985), (108, 0.03261606772570161), (1617, 0.032479112627717036), (1119, 0.032450158391347614), (2832, 0.0324491020854767), (311, 0.032415558772335804), (3473, 0.032411017994566096), (4061, 0.03235140570884925), (495, 0.032342111764553184), (4495, 0.032318296011538426), (3618, 0.032310688367824136), (0, 0.03229579644860707), (70, 0.03215936323229855), (2111, 0.03212715971167248), (2163, 0.03208529158691974), (3505, 0.03205359559048307), (3509, 0.03197052692536307), (922, 0.031966033332557035), (1294, 0.03195472510983312), (128, 0.03189065672879913), (2995, 0.0318738167704259), (168, 0.031873786210526306), (503, 0.031859257248628696), (2761, 0.03183573319671583), (4, 0.03181599223363476), (4788, 0.031794117990322134), (150, 0.03174893989603526), (201, 0.031742888306347056), (735, 0.03174194204026017), (3232, 0.03171854163770062), (4042, 0.03166542309454251), (635, 0.03164706390233992), (3945, 0.03143880424275709), (3421, 0.03143877900012849), (1984, 0.031391182648260955), (1518, 0.031369439413560046), (490, 0.03135053334803914), (149, 0.03133111699857222), (36, 0.031252233451102195), (3636, 0.03125213707541446), (775, 0.03125172381523368), (1259, 0.031227121598415057), (212, 0.031211324999396987), (1034, 0.031189977912605395), (59, 0.031169185955729664), (1332, 0.03114507643230014), (2684, 0.031142322581734723), (813, 0.031141635621381662), (219, 0.03112708021457932), (1250, 0.031115710501120813), (1005, 0.031046220991323203), (2451, 0.031014025186680404), (1986, 0.03096228070088476), (366, 0.03096056708660701), (228, 0.030922447007768084), (1303, 0.030881154255100275), (125, 0.030868053059685638), (123, 0.030785532125086872), (2735, 0.030725244417720596), (920, 0.030720450244166628), (334, 0.030682150193678474), (2561, 0.030670698860359977), (2372, 0.030484487387474307), (4235, 0.030460651829265706), (345, 0.03045947981854056), (487, 0.030448819097262776), (3526, 0.030410055784469286), (412, 0.030368887821126046), (1093, 0.03034019794452572), (393, 0.030310366226266695), (146, 0.03027982428539639), (3836, 0.030229265323092724), (2794, 0.03020311594460491), (1922, 0.03012829089784123), (1201, 0.030122557052595797), (3893, 0.03003383167970886), (493, 0.030005232584611016), (342, 0.02997572783442531), (3575, 0.029954512679801506), (27, 0.029945938769572685), (2654, 0.02988210291079014), (577, 0.02986396554311785), (581, 0.02985550112896601), (4769, 0.029852695427926568), (1001, 0.029841808595457597), (2334, 0.02983740101198113), (593, 0.02963025095999405), (419, 0.029623909851286826), (107, 0.029610515548111373), (878, 0.029605313636739922), (4137, 0.029582910156279542), (52, 0.029558620317564926), (965, 0.02947847157412595), (1285, 0.02947128197874264), (2327, 0.02946238245821122), (1790, 0.029406378375272595), (211, 0.029391423015051654), (4482, 0.0293832000297256), (967, 0.029339080522371667), (1925, 0.029267642877155768), (1440, 0.029199323286284204), (1750, 0.029194190765688348), (3130, 0.029174835679538297), (1439, 0.029131476242927622), (699, 0.02912045059822115), (1079, 0.02908468907326838), (400, 0.029081034183566667), (4734, 0.02905609756972865), (414, 0.02903941163990793), (3441, 0.02898374492984834), (799, 0.02897650736993783), (2375, 0.02896810880667073), (225, 0.02892117260947699), (2479, 0.028905224288099843), (3566, 0.02889906466708453), (2815, 0.02889381100650036), (562, 0.028859761725330998), (1819, 0.028836026538321603), (1191, 0.028832268437356402), (1155, 0.028760709311989128), (2128, 0.02873860702106335), (4425, 0.028736544108780026), (1044, 0.028704249253319835), (3305, 0.028677377901330965), (4467, 0.028670826017519132), (4077, 0.02850706964511581), (2047, 0.02846866189925667), (3582, 0.028437004984939257), (461, 0.028433543829524097), (3237, 0.02840796123747523), (4400, 0.02833707393379697), (2912, 0.02829740434053586), (1880, 0.028284893773874047), (165, 0.028273144719267652), (931, 0.02825877685220863), (67, 0.028230384122127007), (1068, 0.02808317401880346), (1237, 0.028066311253097324), (4081, 0.02806477199068283), (32, 0.028052126365086392), (200, 0.02802386402300029), (3988, 0.027989304811838575), (4344, 0.027976457582971098), (4046, 0.027950795710284575), (1177, 0.02793479449069928), (2961, 0.027858469053542053), (2289, 0.02778773438367284), (3181, 0.027766940476973718), (3245, 0.027741651809877334), (4440, 0.02773649665807473), (1827, 0.027674302057284), (306, 0.02765504464143632), (1687, 0.02762262553841148), (777, 0.027619074911807557), (1507, 0.027600320816531614), (3089, 0.02752549954541355), (3361, 0.02749860346789227), (1171, 0.02749180880473248), (3318, 0.027491354663031084), (415, 0.02748488763466647), (4187, 0.027461248500798063), (2758, 0.02743992019475129), (51, 0.027432051694699693), (2591, 0.027401199364896333), (4728, 0.027336314802169637), (2575, 0.02728663996523155), (4160, 0.027271380496649462), (3260, 0.02725234991953566), (1468, 0.027246223169100754), (778, 0.027229436845970914), (3350, 0.027201097522729693), (4195, 0.02719912920582242), (305, 0.02718581588023705), (263, 0.027171939340130187), (233, 0.027170820633253358), (4552, 0.02716436800718743), (1014, 0.02715153183265738), (249, 0.027128481794969156), (2731, 0.02702171700474993), (1002, 0.027006279257561147), (2077, 0.026986639600744593), (1569, 0.026983284175008445), (3006, 0.026975321956861316), (1496, 0.026953569786239622), (601, 0.026891455836907885), (2578, 0.026862339300184696), (300, 0.026856805141405045), (2320, 0.026831779189780317), (939, 0.026822088441039508), (609, 0.02681003466592808), (1852, 0.0268065127965525), (256, 0.02679505630702151), (319, 0.026785619897612675), (82, 0.026753415454277014), (3804, 0.02672354678737018), (87, 0.026679850773634016), (1531, 0.026664248865195507), (2755, 0.026621615665148313), (3439, 0.026607955784706164), (362, 0.026580766546355196), (2403, 0.026561226173152916), (222, 0.026542189167100813), (313, 0.026512773021282375), (1377, 0.02651197580088155), (380, 0.026508922997980248), (1131, 0.026505525820377594), (1399, 0.026468984631731488), (4218, 0.02641654728761681), (3444, 0.026392610655735834), (97, 0.026391290678116568), (1354, 0.026381600261421636), (3998, 0.02635719695125107), (480, 0.026274742612889534), (740, 0.026254887896969583), (196, 0.02624692415843478), (2213, 0.02616846170136907), (4169, 0.026160090206273037), (1058, 0.026156087641627114), (4039, 0.02615094509073425), (1296, 0.02613767945399824), (371, 0.026080660486806934), (1826, 0.026077888868612953), (2454, 0.026067330823454606), (657, 0.026024838767402737), (2198, 0.026009591884810106), (3795, 0.02600157108466583), (410, 0.025915824763975297), (43, 0.02590880432131621), (1344, 0.02588788316653814), (1198, 0.025809323574734436), (476, 0.025798165512563573), (838, 0.025795818454359448), (4693, 0.0257842397447261), (3986, 0.025754290623217362), (230, 0.0257252370801356), (2245, 0.025685884426851706), (665, 0.025679008681071813), (1070, 0.02564849597500901), (266, 0.025608291432904266), (1633, 0.025562206342364294), (2878, 0.025525120988540248), (74, 0.025501743558833494), (426, 0.02545725971993652), (1642, 0.025444544998843775), (4669, 0.02544416085949487), (23

In [57]:
#key is x=similarity score x[0]=first element that is index
#print the name of similar movies based on the index

print("Movies suggested for you:")
i=1
#getting movie name by index
for movie in sorted_similar_movies:

    index=movie[0] #represent first value(0,1.0000)
    title_from_index=movies_data[movies_data.index==index]['title'].values[0]
    if(i<30):   #first 30 similar movies
        print(i,'.',title_from_index)
        i+=1

Movies suggested for you:
1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . X-Men
10 . X-Men: Apocalypse
11 . X2
12 . The Incredible Hulk
13 . The Helix... Loaded
14 . X-Men: Days of Future Past
15 . X-Men: First Class
16 . Captain America: The First Avenger
17 . Deadpool
18 . Guardians of the Galaxy
19 . Thor: The Dark World
20 . X-Men: The Last Stand
21 . Made
22 . Southland Tales
23 . Tropic Thunder
24 . G-Force
25 . The Amazing Spider-Man 2
26 . Kick-Ass 2
27 . X-Men Origins: Wolverine
28 . Zoom
29 . Fantastic Four

Movie Recommendation System

In [58]:
movie_name=input("enter your favourite movie name:")

list_of_all_titles=movies_data['title'].tolist()

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
close_match=find_close_match[0]
index_of_movie = movies_data[movies_data.title == close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_of_movie]))

sorted_similar_movies=sorted(similarity_score, key = lambda x:x[1],reverse=True)


print("Movies suggested for you:")
i=1
for movie in sorted_similar_movies:

    index=movie[0] #represent first value(0,1.0000)
    title_from_index=movies_data[movies_data.index==index]['title'].values[0]
    if(i<30):   #first 30 similar movies
        print(i,'.',title_from_index)
        i+=1

enter your favourite movie name:bat man
Movies suggested for you:
1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . A History of Violence
8 . Superman
9 . Bedazzled
10 . Man of Steel
11 . Suicide Squad
12 . Beetlejuice
13 . The Postman Always Rings Twice
14 . Salton Sea
15 . Jonah Hex
16 . Spider-Man 3
17 . Superman Returns
18 . Mars Attacks!
19 . Spider-Man 2
20 . Exorcist II: The Heretic
21 . Reds
22 . Superman III
23 . Superman II
24 . Something's Gotta Give
25 . Multiplicity
26 . I Dreamed of Africa
27 . Catwoman
28 . Batman Forever
29 . The One